### ISSUE TITLE
Panic on operator binary when adding custom annotations to Service

### ISSUE THREAD

**Issue by timjohncurtis** [tarantool/tarantool-operator#13]
When attempting to add custom annotations to the `Service` in the example to use consul auto service discovery, the operator binary panics. 

Modified `examples/kv/deployment.yaml` to include the consul annotations as below:
```
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    tarantool.io/role: "router"
  annotations:
    consul.hashicorp.com/service-tags: "kvstore,router"
spec:
  ports:
    - port: 8081
      name: web
      protocol: TCP
  selector:
    tarantool.io/role: "router"
```

the panic trace:
```
{"level":"info","ts":1576754904.0431921,"logger":"controller_role","msg":"Got selector","Request.Namespace":"default","Request.Name":"storage","selector":"tarantool.io/replicaset-template=storage-template"}
{"level":"error","ts":1576754904.0437276,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"cluster-controller","request":"default/examples-kv-cluster","error":"Operation cannot be fulfilled on endpoints \"examples-kv-cluster\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1576754904.6028752,"logger":"controller_role","msg":"Reconciling Role","Request.Namespace":"default","Request.Name":"routers"}
{"level":"info","ts":1576754904.6053317,"logger":"controller_role","msg":"Got selector","Request.Namespace":"default","Request.Name":"routers","selector":"tarantool.io/replicaset-template=router-template"}
{"level":"info","ts":1576754905.0440688,"logger":"controller_cluster","msg":"Reconciling Cluster","Request.Namespace":"default","Request.Name":"examples-kv-cluster"}
{"level":"info","ts":1576754905.0441573,"logger":"controller_cluster","msg":"Already owned","Request.Namespace":"default","Request.Name":"examples-kv-cluster","Role.Name":"storage"}
{"level":"info","ts":1576754905.0441651,"logger":"controller_cluster","msg":"Already owned","Request.Namespace":"default","Request.Name":"examples-kv-cluster","Role.Name":"routers"}
{"level":"info","ts":1576754905.0441687,"logger":"controller_cluster","msg":"Roles reconciled, moving to pod reconcile","Request.Namespace":"default","Request.Name":"examples-kv-cluster"}
E1219 11:28:25.044325       1 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522
/usr/local/Cellar/go/1.12.5/libexec/src/runtime/map_faststr.go:204
/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/pkg/controller/cluster/cluster_controller.go:232
/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 274 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x13e8860, 0x177e000)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/tarantool/tarantool-operator/pkg/controller/cluster.(*ReconcileCluster).Reconcile(0xc000594920, 0xc000c2d8a9, 0x7, 0xc000f189a0, 0x13, 0x23f3d00, 0xc00035fed0, 0x43dab3, 0xc00035ff30)
	/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/pkg/controller/cluster/cluster_controller.go:232 +0x25e4
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000427900, 0x0)
	/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x1cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000312290)
	/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000312290, 0x3b9aca00, 0x0, 0xc000511a01, 0xc000085da0)
	/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000312290, 0x3b9aca00, 0xc000085da0)
	/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/Users/v.tyubek/Development/go/src/github.com/tarantool/tarantool-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x311```

**Comment by bhavenger** [comment]
I have similar problem. I just changed namespace for deployments.

**Comment by timjohncurtis** [comment]
I fixed this in the big merge from the lkwd fork, I will close
